### ISSUE TITLE
Define git merge compatible storage format

### ISSUE THREAD

**Issue by martin-lysk** [opral/inlang#3965]
MESDK-114
See loom for more infos: [https://www.loom.com/share/2927ef8417a4456589f8e2a5fc0a186a?sid=100077c8-01aa-4c83-9417-44ba577046d8](https://www.loom.com/share/2927ef8417a4456589f8e2a5fc0a186a?sid=100077c8-01aa-4c83-9417-44ba577046d8)

**Term definition:**
A record is an atomic entity in a **database**. Operations on such an entity can happen sequencialy but not in parallel. Updates in parallel should raise a conflict to the application level.

What represents an entity and should be atomic needs to be carefully defined during the design of the data model.

In terms of inlang an atom should most likely be a message:

A change in one part of a message, like editing/removing or adding a variant can usually not happen independently. Changes on separate languages - namely spoken, in separate messages - often do not relate.

### 1\. A Merge of edits in different records should not lead to conflicts

Example:

User Alice changes recordA

```
 recordA.name = "Max Mustermann"
```

User Bob changes recordB

```
 recordB.name = "Maria Musterman"
```

Should be merged on database level without conflicts.

In inlang:

If one translator changes a variant in spanish and another changes a variant in german in the same message bundle auto merge should be possible - no conflict expected

### 2\. Parallel creation of records should not lead to Conflicts

Example:

User Alice creates recordA

```
 recordA = new User("Max Mustermann")
```

User Bob creates recordB

```
 recordA = new User("Maria Mustermann")
```

* we expect **no** conflicts on merge

In inlang:

Two translators a german and an english one should be able to add a message without a conflicts.

### 

### 3\. A deletion and a creation happening in parallel should not lead to conflicts

In inlang:

if a translator deletes a message (german one) while another inserts a spanish one

### 4.1. It should raise a conflict when editing the same property

Examples

User Alice changes the name property on recordA and recordB

```
recordA.name = "Max Moritz Mustermann"
recordB.name = "Maria Magdalena Musterman"
```

User Bob changes recordA and recordB on the same property

```
 recordA.name = "Max, Mustermann"
 recordB.name = "Maria, Musterman"
```

* we expect **two** conflicts, one on recordA and one on recordB

### 4.2. It should raise a conflict when editing different properties

User Alice changes name on recordA

```
recordA.name = "Max Moritz Mustermann"
```

User Bob changes age (a different property) on recordA

```
 recordA.age = 25
```

* We expect **one** conflict, on recordA - needs to be resolved by the application level
* If two messages are edited in parallel each message should have its dedicated conflict marker

### 5\. A conflicting file, merged by the default git tools, should be readable by our tools

If a merge leads to a conflict application level needs to be able to handle it. A conflict in json will lead to an unreadable file:

```
 {
    "id": "crazy_frog_jumping",
    "alias": {},
    "messages": [
      {
<<<<<<< ./left.txt
        "locale": "de",
=======
        "locale": "es",
>>>>>>> ./right.txt
        "declarations": [],
        "selectors": [],
        "variants": [
          {
            "match": [],
            "pattern": [
              {
                "type": "text",
<<<<<<< ./left.txt
                "value": "Guten Morgen"
=======
                "value": "Buenas dias"
>>>>>>> ./right.txt
              }
            ]
          }
        ]
      }
    ]
}
```

\- if message file conflicts because of simulatanous edits fink should still function

### Proposal

A first draft of a format definition:

![Screenshot 2024-05-29 at 15.09.25.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/39a5880e-1636-422e-9cfe-d156080e487b/a9bb732b-dbc2-4db9-b8c7-59117ff856bf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8zOWE1ODgwZS0xNjM2LTQyMmUtOWNmZS1kMTU2MDgwZTQ4N2IvYTliYjczMmItZGJjMi00ZGI5LWI4YzctNTkxMTdmZjg1NmJmIiwiaWF0IjoxNzE2OTg4MjQ5LCJleHAiOjMzMjg3NTQ4MjQ5fQ.O-MtzN5OQEFofKF1kFCJYMd4GldJnVSQBm69Dmmq8fs "=883x")

**Comment by jldec** [comment]
@samuel.stroschein I agree with the overall strategy (1.) of making the inlang file format work nicely with vanilla git.

My concern is that it feels like we are jumping directly into a new non-JSON format when a simpler JSON-based solution **might** cover many of the requirements above, like avoiding merge conflicts in most cases, and triggering merge conflicts in those cases we want.

You mentioned:

> while trying to delay "app scoped" merge resolution in inlang until users run into the problem.

Do I interpret ☝️ correctly, that (for now) we should try to rely on developers to use available git merge conflict resolution tools, instead of extending the SDK to parse files with merge conflicts, and sending conflicts to the Fink UI? 

If the simple solution doesn't work, I'll be fine exploring new formats as well, but I'd prefer if we validated that first. To help with that, I've adjusted the v2-persistence serializer to [add linefeeds](https://github.com/opral/monorepo/pull/2801/commits/1a405ee33e16b6e84499c4f6cc1c18744f924b15#diff-490b75f6e01e8c5e24c7dde1427e5b929c59fc0296072d6da90f4c20d93ecb95) between bundles and messages in the JSON, so we can try out how that works with git merge conflict detection and resolution. The change is in the PR, screenshot added below (using GitHub)

![Screenshot 2024-05-30 at 14 51 52](https://github.com/opral/inlang/assets/849592/270a03f6-75d1-4c98-bdf9-270f90f3dab6)
